### ISSUE TITLE
How to  remove UMI in paired-end sequencing data?

### ISSUE THREAD

**Issue by wcxiaoping** [pinellolab/AmpUMI#2]

**Comment by kclem** [comment]
First, merge your R1 and R2 using [FLASh](https://ccb.jhu.edu/software/FLASH/) or a similar tool. These merged reads can then be used as input for AmpUMI.

**Comment by wcxiaoping** [comment]
I'll try it. Thank you very much for your reply.

**Comment by kclem** [comment]
For scRNA-seq or other applications where paired reads may not overlap (and cannot be merged before deduplicating) there are other tools (e.g. [UMI-tools](https://github.com/CGATOxford/UMI-tools/blob/master/doc/QUICK_START.md#paired-end-sequencing)) that are designed for those use cases.
