### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kasenriemersma** [pinellolab/AmpUMI#3]
I would like to use AmpUMI code in a UMI pipeline, but I do not see an open source license listed. Might I suggest either adding an open source license, or stating in the README that the code is not licensed for open source use? Thank you. https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository https://choosealicense.com/

**Comment by lucapinello** [comment]
Thanks for the suggestion! We have added the missing license file.
