### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by LordofBastion** [pinellolab/AmpUMI#6]
Hello, could you help me please? After installing the program and specifying the path, the program does not start. When I write AmpUMI h- and other, it says that there is no such command. What is the problem?

**Comment by kclem** [comment]
Hi @LordofBastion, 

- What operating system are you running on? 
- What command did you use to install AmpUMI?
- What error do you see when you run `AmpUMI -h` (can you copy and paste it here)?
- What happens when you run `which AmpUMI`?

**Comment by LordofBastion** [comment]
While I'm writing answer, the program started working. Do not know how. Sorry for disturbing you.
